export type DependencyStatus = "dependency_detected" | "dependency_unresolved";

export type NdcLabel = "ndc_1_operator_dependent" | "not_computed";

export type RuleEngineMetadata = {
  name: "adap-citizen-dependency-rules";
  version: "0.1.1";
  deterministic: true;
  reproducible_by_design: true;
  externally_reproduced: false;
  reproduction_status: "not_yet_independently_reproduced";
  warning: string;
};

export type ClassificationBasis = {
  signal: string;
  derivation: "deterministic_rule";
  rule_id: string;
  rule_version: "0.1.1";
  external_verification: false;
  warning: string;
};

export type DependencyRuleInput = {
  operator_domain?: string;
  public_key_source_url?: string;
  envelope_source_url?: string;
  reconstruction_rules_url?: string;
  timestamp_source_url?: string;
};

export type DependencyClassification = {
  dependency_status: DependencyStatus;
  ndc_label: NdcLabel;
  summary: string;
  derivation: "deterministic_rule";
  external_verification: false;
  does_not_prove: string[];
  warning: string;
  classification_basis: ClassificationBasis[];
};

export type DependencyRuleEngineResult = {
  rule_engine: RuleEngineMetadata;
  dependency_classification: DependencyClassification;
};

export const RULE_ENGINE_METADATA: RuleEngineMetadata = {
  name: "adap-citizen-dependency-rules",
  version: "0.1.1",
  deterministic: true,
  reproducible_by_design: true,
  externally_reproduced: false,
  reproduction_status: "not_yet_independently_reproduced",
  warning:
    "This rule engine is designed to be reproducible, but no independent reproduction is claimed unless externally demonstrated.",
};

const DOES_NOT_PROVE = [
  "independence",
  "manipulation",
  "fraud",
  "wrongdoing",
  "truth",
  "fairness",
  "legality",
  "correctness",
  "accountability",
  "external_reproduction",
];

function normalizeHostname(value?: string): string | null {
  if (!value || value.trim() === "") return null;

  try {
    const withProtocol = value.includes("://") ? value : `https://${value}`;
    return new URL(withProtocol).hostname.toLowerCase();
  } catch {
    return null;
  }
}

function sameDomain(a?: string, b?: string): boolean {
  const hostA = normalizeHostname(a);
  const hostB = normalizeHostname(b);

  if (!hostA || !hostB) return false;

  return hostA === hostB;
}

function buildBasis(
  signal: string,
  rule_id: string,
  warning: string
): ClassificationBasis {
  return {
    signal,
    derivation: "deterministic_rule",
    rule_id,
    rule_version: "0.1.1",
    external_verification: false,
    warning,
  };
}

export function classifyDependency(
  input: DependencyRuleInput
): DependencyRuleEngineResult {
  const classification_basis: ClassificationBasis[] = [];

  if (sameDomain(input.public_key_source_url, input.operator_domain)) {
    classification_basis.push(
      buildBasis(
        "public_key_source_matches_operator_domain",
        "ADAP-CV-DEP-001",
        "This signal was generated by the verifier. Same-domain public key hosting is a dependency indicator, not proof of bad intent."
      )
    );
  }

  if (classification_basis.length > 0) {
    return {
      rule_engine: RULE_ENGINE_METADATA,
      dependency_classification: {
        dependency_status: "dependency_detected",
        ndc_label: "ndc_1_operator_dependent",
        summary:
          "The available verification path appears to depend on the organization whose decision is being reviewed.",
        derivation: "deterministic_rule",
        external_verification: false,
        does_not_prove: DOES_NOT_PROVE,
        warning:
          "This classification is generated by deterministic verifier rules. It is a conservative dependency signal, not independently verified proof.",
        classification_basis,
      },
    };
  }

  return {
    rule_engine: RULE_ENGINE_METADATA,
    dependency_classification: {
      dependency_status: "dependency_unresolved",
      ndc_label: "not_computed",
      summary:
        "The verifier could not determine whether the verification path is structurally independent.",
      derivation: "deterministic_rule",
      external_verification: false,
      does_not_prove: DOES_NOT_PROVE,
      warning:
        "No independence claim is made. The dependency state remains unresolved.",
      classification_basis,
    },
  };
}
